sudo: require
language: cpp
compiler:
  - gcc
branches:
  only:
  - master

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
before_install:
  - sudo apt-get install libsfml-dev
script:
<<<<<<< HEAD
  - cd build && cmake .. && make
=======
  - cmake . && make
>>>>>>> 14c9370e46fcea7a2e44652a711bfecafecbb722
