dist: trusty
sudo: require
language: cpp
compiler:
  - gcc
branches:
  only:
  - master

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          packages:
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
before_install:
  - sudo apt-get install libsfml-dev
script:
  - cd build && cmake .. && make
