version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: gcc:9
    steps:
      - checkout
      - run:
          name: Set up
          command: |
            git submodule sync; git submodule update --init # initialize git submodules
            apt update -y
            apt-get install cmake -y
            apt install libsfml-dev -y
            apt install libyaml-cpp-dev -y
            apt install libgtest-dev -y
            mkdir build && cd build && cmake .. && make
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
