version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: circleci/ruby:stretch
    steps:
      - checkout
      - run:
          name: Set up
          command: |
            sudo apt-get update
            git submodule sync; git submodule update --init # initialize git submodules
            sudo apt-get install cmake
            sudo apt-get install libsfml-dev
            sudo apt-get install libyaml-cpp-dev
            sudo apt-get install libgtest-dev
            mkdir build && cd build && cmake .. && make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
